//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergomonitoringXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class param_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal param_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergomonitoringXP.param_strings", typeof(param_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of interharmonic groups of order {0}.
        /// </summary>
        internal static string avg_square_order_x_x {
            get {
                return ResourceManager.GetString("avg_square_order_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between zero sequence voltage and current.
        /// </summary>
        internal static string str_an_u_0_i_0 {
            get {
                return ResourceManager.GetString("str_an_u_0_i_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between positive sequence voltage and current.
        /// </summary>
        internal static string str_an_u_1_i_1 {
            get {
                return ResourceManager.GetString("str_an_u_1_i_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between negative sequence voltage and current.
        /// </summary>
        internal static string str_an_u_2_i_2 {
            get {
                return ResourceManager.GetString("str_an_u_2_i_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between voltage and current of {0} harmonic.
        /// </summary>
        internal static string str_an_u_x_1_i_x_1 {
            get {
                return ResourceManager.GetString("str_an_u_x_1_i_x_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between 1st voltage and 1st current harmonics, phases A.
        /// </summary>
        internal static string str_an_u1_a_i1_a {
            get {
                return ResourceManager.GetString("str_an_u1_a_i1_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between 1st voltage harmonics, phases A and B.
        /// </summary>
        internal static string str_an_u1_a_u1_b {
            get {
                return ResourceManager.GetString("str_an_u1_a_u1_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between 1st voltage and 1st current harmonics, phases B.
        /// </summary>
        internal static string str_an_u1_b_i1_b {
            get {
                return ResourceManager.GetString("str_an_u1_b_i1_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between 1st voltage harmonics, phases B and C.
        /// </summary>
        internal static string str_an_u1_b_u1_c {
            get {
                return ResourceManager.GetString("str_an_u1_b_u1_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between 1st voltage and 1st current harmonics, phases C.
        /// </summary>
        internal static string str_an_u1_c_i1_c {
            get {
                return ResourceManager.GetString("str_an_u1_c_i1_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between 1st voltage harmonics, phases C and A.
        /// </summary>
        internal static string str_an_u1_c_u1_a {
            get {
                return ResourceManager.GetString("str_an_u1_c_u1_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of zero sequence power.
        /// </summary>
        internal static string str_angle_p_0 {
            get {
                return ResourceManager.GetString("str_angle_p_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of positive sequence power.
        /// </summary>
        internal static string str_angle_p_1 {
            get {
                return ResourceManager.GetString("str_angle_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of negative sequence power.
        /// </summary>
        internal static string str_angle_p_2 {
            get {
                return ResourceManager.GetString("str_angle_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between phase voltage UA and current IA.
        /// </summary>
        internal static string str_angle_ua_ia {
            get {
                return ResourceManager.GetString("str_angle_ua_ia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between phase voltages UA and UB.
        /// </summary>
        internal static string str_angle_ua_ub {
            get {
                return ResourceManager.GetString("str_angle_ua_ub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between line voltage AB and current IA.
        /// </summary>
        internal static string str_angle_uab_ia {
            get {
                return ResourceManager.GetString("str_angle_uab_ia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between line voltages AB and CB.
        /// </summary>
        internal static string str_angle_uab_ucb {
            get {
                return ResourceManager.GetString("str_angle_uab_ucb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between phase voltage UB and current IB.
        /// </summary>
        internal static string str_angle_ub_ib {
            get {
                return ResourceManager.GetString("str_angle_ub_ib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between phase voltages UB and UC.
        /// </summary>
        internal static string str_angle_ub_uc {
            get {
                return ResourceManager.GetString("str_angle_ub_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between phase voltage UC and current IC.
        /// </summary>
        internal static string str_angle_uc_ic {
            get {
                return ResourceManager.GetString("str_angle_uc_ic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between phase voltages UC and UA.
        /// </summary>
        internal static string str_angle_uc_ua {
            get {
                return ResourceManager.GetString("str_angle_uc_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between line voltage CB and current IC.
        /// </summary>
        internal static string str_angle_ucb_ic {
            get {
                return ResourceManager.GetString("str_angle_ucb_ic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, phase А.
        /// </summary>
        internal static string str_avg_square_a {
            get {
                return ResourceManager.GetString("str_avg_square_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, line А.
        /// </summary>
        internal static string str_avg_square_ab {
            get {
                return ResourceManager.GetString("str_avg_square_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, phase В.
        /// </summary>
        internal static string str_avg_square_b {
            get {
                return ResourceManager.GetString("str_avg_square_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, line В.
        /// </summary>
        internal static string str_avg_square_bc {
            get {
                return ResourceManager.GetString("str_avg_square_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, phase С.
        /// </summary>
        internal static string str_avg_square_c {
            get {
                return ResourceManager.GetString("str_avg_square_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, line С.
        /// </summary>
        internal static string str_avg_square_ca {
            get {
                return ResourceManager.GetString("str_avg_square_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of subharmonic group, midpoint wire current.
        /// </summary>
        internal static string str_avg_square_n {
            get {
                return ResourceManager.GetString("str_avg_square_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency deviation.
        /// </summary>
        internal static string str_d_f {
            get {
                return ResourceManager.GetString("str_d_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage deviation, phase A.
        /// </summary>
        internal static string str_d_u_a {
            get {
                return ResourceManager.GetString("str_d_u_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of line voltage UAB.
        /// </summary>
        internal static string str_d_u_ab {
            get {
                return ResourceManager.GetString("str_d_u_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage deviation, phase B.
        /// </summary>
        internal static string str_d_u_b {
            get {
                return ResourceManager.GetString("str_d_u_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of line voltage UBC.
        /// </summary>
        internal static string str_d_u_bc {
            get {
                return ResourceManager.GetString("str_d_u_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage deviation, phase C.
        /// </summary>
        internal static string str_d_u_c {
            get {
                return ResourceManager.GetString("str_d_u_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of line voltage UCA.
        /// </summary>
        internal static string str_d_u_ca {
            get {
                return ResourceManager.GetString("str_d_u_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - phase A [absolute].
        /// </summary>
        internal static string str_d_u_neg_a {
            get {
                return ResourceManager.GetString("str_d_u_neg_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - line AB [absolute].
        /// </summary>
        internal static string str_d_u_neg_ab {
            get {
                return ResourceManager.GetString("str_d_u_neg_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - phase B [absolute].
        /// </summary>
        internal static string str_d_u_neg_b {
            get {
                return ResourceManager.GetString("str_d_u_neg_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - line BC [absolute].
        /// </summary>
        internal static string str_d_u_neg_bc {
            get {
                return ResourceManager.GetString("str_d_u_neg_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - phase C [absolute].
        /// </summary>
        internal static string str_d_u_neg_c {
            get {
                return ResourceManager.GetString("str_d_u_neg_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - line CA [absolute].
        /// </summary>
        internal static string str_d_u_neg_ca {
            get {
                return ResourceManager.GetString("str_d_u_neg_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - phase A [absolute].
        /// </summary>
        internal static string str_d_u_pos_a {
            get {
                return ResourceManager.GetString("str_d_u_pos_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - line AB [absolute].
        /// </summary>
        internal static string str_d_u_pos_ab {
            get {
                return ResourceManager.GetString("str_d_u_pos_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - phase B [absolute].
        /// </summary>
        internal static string str_d_u_pos_b {
            get {
                return ResourceManager.GetString("str_d_u_pos_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - line BC [absolute].
        /// </summary>
        internal static string str_d_u_pos_bc {
            get {
                return ResourceManager.GetString("str_d_u_pos_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - phase C [absolute].
        /// </summary>
        internal static string str_d_u_pos_c {
            get {
                return ResourceManager.GetString("str_d_u_pos_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - line CA [absolute].
        /// </summary>
        internal static string str_d_u_pos_ca {
            get {
                return ResourceManager.GetString("str_d_u_pos_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage deviation.
        /// </summary>
        internal static string str_d_u_y {
            get {
                return ResourceManager.GetString("str_d_u_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string str_f {
            get {
                return ResourceManager.GetString("str_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency, phase А.
        /// </summary>
        internal static string str_f_a {
            get {
                return ResourceManager.GetString("str_f_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency, line АB.
        /// </summary>
        internal static string str_f_ab {
            get {
                return ResourceManager.GetString("str_f_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency, phase B.
        /// </summary>
        internal static string str_f_b {
            get {
                return ResourceManager.GetString("str_f_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency, line BC.
        /// </summary>
        internal static string str_f_bc {
            get {
                return ResourceManager.GetString("str_f_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency, phase C.
        /// </summary>
        internal static string str_f_c {
            get {
                return ResourceManager.GetString("str_f_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency, line CA.
        /// </summary>
        internal static string str_f_ca {
            get {
                return ResourceManager.GetString("str_f_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero sequence current.
        /// </summary>
        internal static string str_i_0 {
            get {
                return ResourceManager.GetString("str_i_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive sequence current.
        /// </summary>
        internal static string str_i_1 {
            get {
                return ResourceManager.GetString("str_i_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative sequence current.
        /// </summary>
        internal static string str_i_2 {
            get {
                return ResourceManager.GetString("str_i_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of phase A current.
        /// </summary>
        internal static string str_i_a {
            get {
                return ResourceManager.GetString("str_i_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st current harmonic, phase A.
        /// </summary>
        internal static string str_i_a_1harm {
            get {
                return ResourceManager.GetString("str_i_a_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified RMS of phase A current.
        /// </summary>
        internal static string str_i_a_avdirect {
            get {
                return ResourceManager.GetString("str_i_a_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of phase A current, constant component.
        /// </summary>
        internal static string str_i_a_const {
            get {
                return ResourceManager.GetString("str_i_a_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of phase B current.
        /// </summary>
        internal static string str_i_b {
            get {
                return ResourceManager.GetString("str_i_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st current harmonic, phase B.
        /// </summary>
        internal static string str_i_b_1harm {
            get {
                return ResourceManager.GetString("str_i_b_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified RMS of phase B current.
        /// </summary>
        internal static string str_i_b_avdirect {
            get {
                return ResourceManager.GetString("str_i_b_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of phase B current, constant component.
        /// </summary>
        internal static string str_i_b_const {
            get {
                return ResourceManager.GetString("str_i_b_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of phase C current.
        /// </summary>
        internal static string str_i_c {
            get {
                return ResourceManager.GetString("str_i_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st current harmonic, phase C.
        /// </summary>
        internal static string str_i_c_1harm {
            get {
                return ResourceManager.GetString("str_i_c_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified RMS of phase C current.
        /// </summary>
        internal static string str_i_c_avdirect {
            get {
                return ResourceManager.GetString("str_i_c_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of phase C current, constant component.
        /// </summary>
        internal static string str_i_c_const {
            get {
                return ResourceManager.GetString("str_i_c_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midpoint wire current.
        /// </summary>
        internal static string str_i_n {
            get {
                return ResourceManager.GetString("str_i_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st harmonic of midpoint wire current.
        /// </summary>
        internal static string str_i_n_1harm {
            get {
                return ResourceManager.GetString("str_i_n_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified midpoint wire current.
        /// </summary>
        internal static string str_i_n_avdirect {
            get {
                return ResourceManager.GetString("str_i_n_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midpoint wire current, constant component.
        /// </summary>
        internal static string str_i_n_const {
            get {
                return ResourceManager.GetString("str_i_n_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual {0} midpoint wire current harmonic ratio.
        /// </summary>
        internal static string str_i_n_x {
            get {
                return ResourceManager.GetString("str_i_n_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st current harmonic, phase A.
        /// </summary>
        internal static string str_i1_a {
            get {
                return ResourceManager.GetString("str_i1_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st current harmonic, phase B.
        /// </summary>
        internal static string str_i1_b {
            get {
                return ResourceManager.GetString("str_i1_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS of 1st current harmonic, phase C.
        /// </summary>
        internal static string str_i1_c {
            get {
                return ResourceManager.GetString("str_i1_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st harmonic of midpoint wire current.
        /// </summary>
        internal static string str_i1_n {
            get {
                return ResourceManager.GetString("str_i1_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If record was marked.
        /// </summary>
        internal static string str_if_record_marked {
            get {
                return ResourceManager.GetString("str_if_record_marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero sequence voltage ratio.
        /// </summary>
        internal static string str_k_0u {
            get {
                return ResourceManager.GetString("str_k_0u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative sequence voltage ratio.
        /// </summary>
        internal static string str_k_2u {
            get {
                return ResourceManager.GetString("str_k_2u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of current, phase A.
        /// </summary>
        internal static string str_k_ia {
            get {
                return ResourceManager.GetString("str_k_ia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of current, phase B.
        /// </summary>
        internal static string str_k_ib {
            get {
                return ResourceManager.GetString("str_k_ib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of current, phase C.
        /// </summary>
        internal static string str_k_ic {
            get {
                return ResourceManager.GetString("str_k_ic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual {0} current harmonic ratio, phase {1}.
        /// </summary>
        internal static string str_k_ix_x {
            get {
                return ResourceManager.GetString("str_k_ix_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of voltage, phase A.
        /// </summary>
        internal static string str_k_ua {
            get {
                return ResourceManager.GetString("str_k_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of line voltage, AB.
        /// </summary>
        internal static string str_k_uab {
            get {
                return ResourceManager.GetString("str_k_uab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of voltage, phase B.
        /// </summary>
        internal static string str_k_ub {
            get {
                return ResourceManager.GetString("str_k_ub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of line voltage, BC.
        /// </summary>
        internal static string str_k_ubc {
            get {
                return ResourceManager.GetString("str_k_ubc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of voltage, phase C.
        /// </summary>
        internal static string str_k_uc {
            get {
                return ResourceManager.GetString("str_k_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total harmonic distortion of line voltage, CA.
        /// </summary>
        internal static string str_k_uca {
            get {
                return ResourceManager.GetString("str_k_uca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual {0} voltage harmonic ratio, phase {1}.
        /// </summary>
        internal static string str_k_ux_x {
            get {
                return ResourceManager.GetString("str_k_ux_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual {0} line voltage {1} harmonic ratio.
        /// </summary>
        internal static string str_k_uxx_x {
            get {
                return ResourceManager.GetString("str_k_uxx_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total power factor.
        /// </summary>
        internal static string str_kp_12 {
            get {
                return ResourceManager.GetString("str_kp_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power factor, phase A.
        /// </summary>
        internal static string str_kp_a {
            get {
                return ResourceManager.GetString("str_kp_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total power factor.
        /// </summary>
        internal static string str_kp_abc {
            get {
                return ResourceManager.GetString("str_kp_abc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power factor, phase B.
        /// </summary>
        internal static string str_kp_b {
            get {
                return ResourceManager.GetString("str_kp_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power factor, phase C.
        /// </summary>
        internal static string str_kp_c {
            get {
                return ResourceManager.GetString("str_kp_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total power factor.
        /// </summary>
        internal static string str_kp_sum {
            get {
                return ResourceManager.GetString("str_kp_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient for order {0}, midpoint wire current.
        /// </summary>
        internal static string str_order_coeff_x_n {
            get {
                return ResourceManager.GetString("str_order_coeff_x_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient for order {0}, phase {1}.
        /// </summary>
        internal static string str_order_coeff_x_x {
            get {
                return ResourceManager.GetString("str_order_coeff_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient for order {0}, line {1}.
        /// </summary>
        internal static string str_order_coeff_x_xx {
            get {
                return ResourceManager.GetString("str_order_coeff_x_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for order {0}, midpoint wire current.
        /// </summary>
        internal static string str_order_value_x_n {
            get {
                return ResourceManager.GetString("str_order_value_x_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for order {0}, phase {1}.
        /// </summary>
        internal static string str_order_value_x_x {
            get {
                return ResourceManager.GetString("str_order_value_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for order {0}, line {1}.
        /// </summary>
        internal static string str_order_value_x_xx {
            get {
                return ResourceManager.GetString("str_order_value_x_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero sequence power.
        /// </summary>
        internal static string str_p_0 {
            get {
                return ResourceManager.GetString("str_p_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive sequence power.
        /// </summary>
        internal static string str_p_1 {
            get {
                return ResourceManager.GetString("str_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative sequence power.
        /// </summary>
        internal static string str_p_2 {
            get {
                return ResourceManager.GetString("str_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power, phase A.
        /// </summary>
        internal static string str_p_a {
            get {
                return ResourceManager.GetString("str_p_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power, AB.
        /// </summary>
        internal static string str_p_ab {
            get {
                return ResourceManager.GetString("str_p_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power, phase B.
        /// </summary>
        internal static string str_p_b {
            get {
                return ResourceManager.GetString("str_p_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power, phase C.
        /// </summary>
        internal static string str_p_c {
            get {
                return ResourceManager.GetString("str_p_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power, CB.
        /// </summary>
        internal static string str_p_cb {
            get {
                return ResourceManager.GetString("str_p_cb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total active power.
        /// </summary>
        internal static string str_p_sum {
            get {
                return ResourceManager.GetString("str_p_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total active power of {0} harmonic.
        /// </summary>
        internal static string str_p_sum_x {
            get {
                return ResourceManager.GetString("str_p_sum_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power of {0} harmonic, phase {1}.
        /// </summary>
        internal static string str_p_x_x {
            get {
                return ResourceManager.GetString("str_p_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power of {0} harmonic, {1}.
        /// </summary>
        internal static string str_p_xx_x {
            get {
                return ResourceManager.GetString("str_p_xx_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power P1.
        /// </summary>
        internal static string str_p1_3phase {
            get {
                return ResourceManager.GetString("str_p1_3phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power P2.
        /// </summary>
        internal static string str_p2_3phase {
            get {
                return ResourceManager.GetString("str_p2_3phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, angle (order {0}), component 1.
        /// </summary>
        internal static string str_pharm_angle_1_x {
            get {
                return ResourceManager.GetString("str_pharm_angle_1_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, angle (order {0}), component 2.
        /// </summary>
        internal static string str_pharm_angle_2_x {
            get {
                return ResourceManager.GetString("str_pharm_angle_2_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, angle (order {0}), total.
        /// </summary>
        internal static string str_pharm_angle_sum_x {
            get {
                return ResourceManager.GetString("str_pharm_angle_sum_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, angle (order {0}), phase {1}.
        /// </summary>
        internal static string str_pharm_angle_x_x {
            get {
                return ResourceManager.GetString("str_pharm_angle_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, active component (order {0}), component 1.
        /// </summary>
        internal static string str_pharm_p_1_x {
            get {
                return ResourceManager.GetString("str_pharm_p_1_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, active component (order {0}), component 2.
        /// </summary>
        internal static string str_pharm_p_2_x {
            get {
                return ResourceManager.GetString("str_pharm_p_2_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, active component (order {0}), total.
        /// </summary>
        internal static string str_pharm_p_sum_x {
            get {
                return ResourceManager.GetString("str_pharm_p_sum_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, active component (order {0}), phase {1}.
        /// </summary>
        internal static string str_pharm_p_x_x {
            get {
                return ResourceManager.GetString("str_pharm_p_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, reactive component (order {0}), component 1.
        /// </summary>
        internal static string str_pharm_q_1_x {
            get {
                return ResourceManager.GetString("str_pharm_q_1_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, reactive component (order {0}), component 2.
        /// </summary>
        internal static string str_pharm_q_2_x {
            get {
                return ResourceManager.GetString("str_pharm_q_2_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, reactive component (order {0}), total.
        /// </summary>
        internal static string str_pharm_q_sum_x {
            get {
                return ResourceManager.GetString("str_pharm_q_sum_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics power, reactive component (order {0}), phase {1}.
        /// </summary>
        internal static string str_pharm_q_x_x {
            get {
                return ResourceManager.GetString("str_pharm_q_x_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reactive power.
        /// </summary>
        internal static string str_q_12sum {
            get {
                return ResourceManager.GetString("str_q_12sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase A.
        /// </summary>
        internal static string str_q_a {
            get {
                return ResourceManager.GetString("str_q_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase A (for 1st harmonic).
        /// </summary>
        internal static string str_q_a_1harm {
            get {
                return ResourceManager.GetString("str_q_a_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase A (cross-conn. method).
        /// </summary>
        internal static string str_q_a_cross {
            get {
                return ResourceManager.GetString("str_q_a_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase A (geom. method).
        /// </summary>
        internal static string str_q_a_geom {
            get {
                return ResourceManager.GetString("str_q_a_geom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase A (ph. shift method).
        /// </summary>
        internal static string str_q_a_shift {
            get {
                return ResourceManager.GetString("str_q_a_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase B.
        /// </summary>
        internal static string str_q_b {
            get {
                return ResourceManager.GetString("str_q_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase B (for 1st harmonic).
        /// </summary>
        internal static string str_q_b_1harm {
            get {
                return ResourceManager.GetString("str_q_b_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase B (cross-conn. method).
        /// </summary>
        internal static string str_q_b_cross {
            get {
                return ResourceManager.GetString("str_q_b_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase B (geom. method).
        /// </summary>
        internal static string str_q_b_geom {
            get {
                return ResourceManager.GetString("str_q_b_geom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase B (ph. shift method).
        /// </summary>
        internal static string str_q_b_shift {
            get {
                return ResourceManager.GetString("str_q_b_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase C.
        /// </summary>
        internal static string str_q_c {
            get {
                return ResourceManager.GetString("str_q_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase C (for 1st harmonic).
        /// </summary>
        internal static string str_q_c_1harm {
            get {
                return ResourceManager.GetString("str_q_c_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase C (cross-conn. method).
        /// </summary>
        internal static string str_q_c_cross {
            get {
                return ResourceManager.GetString("str_q_c_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase C (geom. method).
        /// </summary>
        internal static string str_q_c_geom {
            get {
                return ResourceManager.GetString("str_q_c_geom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power, phase C (ph. shift method).
        /// </summary>
        internal static string str_q_c_shift {
            get {
                return ResourceManager.GetString("str_q_c_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reactive power.
        /// </summary>
        internal static string str_q_sum {
            get {
                return ResourceManager.GetString("str_q_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reactive power (for 1st harmonic).
        /// </summary>
        internal static string str_q_sum_1harm {
            get {
                return ResourceManager.GetString("str_q_sum_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reactive power (cross-conn. method).
        /// </summary>
        internal static string str_q_sum_cross {
            get {
                return ResourceManager.GetString("str_q_sum_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reactive power (geom. method).
        /// </summary>
        internal static string str_q_sum_geom {
            get {
                return ResourceManager.GetString("str_q_sum_geom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reactive power (ph. shift method).
        /// </summary>
        internal static string str_q_sum_shift {
            get {
                return ResourceManager.GetString("str_q_sum_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage deviation [относительное].
        /// </summary>
        internal static string str_rd_u {
            get {
                return ResourceManager.GetString("str_rd_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of 1st harmonic of phase voltage – phase A [relative].
        /// </summary>
        internal static string str_rd_u_1harm_a {
            get {
                return ResourceManager.GetString("str_rd_u_1harm_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of 1st harmonic of line voltage – line AB [relative].
        /// </summary>
        internal static string str_rd_u_1harm_ab {
            get {
                return ResourceManager.GetString("str_rd_u_1harm_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of 1st harmonic of phase voltage – phase B [relative].
        /// </summary>
        internal static string str_rd_u_1harm_b {
            get {
                return ResourceManager.GetString("str_rd_u_1harm_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of 1st harmonic of line voltage – line BC [relative].
        /// </summary>
        internal static string str_rd_u_1harm_bc {
            get {
                return ResourceManager.GetString("str_rd_u_1harm_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of 1st harmonic of phase voltage – phase C [relative].
        /// </summary>
        internal static string str_rd_u_1harm_c {
            get {
                return ResourceManager.GetString("str_rd_u_1harm_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of 1st harmonic of line voltage – line CA [relative].
        /// </summary>
        internal static string str_rd_u_1harm_ca {
            get {
                return ResourceManager.GetString("str_rd_u_1harm_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - phase A [relative].
        /// </summary>
        internal static string str_rd_u_neg_a {
            get {
                return ResourceManager.GetString("str_rd_u_neg_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - line AB [relative].
        /// </summary>
        internal static string str_rd_u_neg_ab {
            get {
                return ResourceManager.GetString("str_rd_u_neg_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - phase B [relative].
        /// </summary>
        internal static string str_rd_u_neg_b {
            get {
                return ResourceManager.GetString("str_rd_u_neg_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - line BC [relative].
        /// </summary>
        internal static string str_rd_u_neg_bc {
            get {
                return ResourceManager.GetString("str_rd_u_neg_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - phase C [relative].
        /// </summary>
        internal static string str_rd_u_neg_c {
            get {
                return ResourceManager.GetString("str_rd_u_neg_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative voltage deviation - line CA [relative].
        /// </summary>
        internal static string str_rd_u_neg_ca {
            get {
                return ResourceManager.GetString("str_rd_u_neg_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - phase A [relative].
        /// </summary>
        internal static string str_rd_u_pos_a {
            get {
                return ResourceManager.GetString("str_rd_u_pos_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - line AB [relative].
        /// </summary>
        internal static string str_rd_u_pos_ab {
            get {
                return ResourceManager.GetString("str_rd_u_pos_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - phase B [relative].
        /// </summary>
        internal static string str_rd_u_pos_b {
            get {
                return ResourceManager.GetString("str_rd_u_pos_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - line BC [relative].
        /// </summary>
        internal static string str_rd_u_pos_bc {
            get {
                return ResourceManager.GetString("str_rd_u_pos_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - phase C [relative].
        /// </summary>
        internal static string str_rd_u_pos_c {
            get {
                return ResourceManager.GetString("str_rd_u_pos_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive voltage deviation - line CA [relative].
        /// </summary>
        internal static string str_rd_u_pos_ca {
            get {
                return ResourceManager.GetString("str_rd_u_pos_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total apparent power.
        /// </summary>
        internal static string str_s_12sum {
            get {
                return ResourceManager.GetString("str_s_12sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent power, phase A.
        /// </summary>
        internal static string str_s_a {
            get {
                return ResourceManager.GetString("str_s_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent power, phase B.
        /// </summary>
        internal static string str_s_b {
            get {
                return ResourceManager.GetString("str_s_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent power, phase C.
        /// </summary>
        internal static string str_s_c {
            get {
                return ResourceManager.GetString("str_s_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total apparent power.
        /// </summary>
        internal static string str_s_sum {
            get {
                return ResourceManager.GetString("str_s_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coefficient, phase А.
        /// </summary>
        internal static string str_summ_coeff_a {
            get {
                return ResourceManager.GetString("str_summ_coeff_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coefficient, line АB.
        /// </summary>
        internal static string str_summ_coeff_ab {
            get {
                return ResourceManager.GetString("str_summ_coeff_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coefficient, phase В.
        /// </summary>
        internal static string str_summ_coeff_b {
            get {
                return ResourceManager.GetString("str_summ_coeff_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coefficient, line ВC.
        /// </summary>
        internal static string str_summ_coeff_bc {
            get {
                return ResourceManager.GetString("str_summ_coeff_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coefficient, phase С.
        /// </summary>
        internal static string str_summ_coeff_c {
            get {
                return ResourceManager.GetString("str_summ_coeff_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coefficient, line СA.
        /// </summary>
        internal static string str_summ_coeff_ca {
            get {
                return ResourceManager.GetString("str_summ_coeff_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for harmonious subgroups of order &gt; 1.
        /// </summary>
        internal static string str_summ_for_order_more_1_a {
            get {
                return ResourceManager.GetString("str_summ_for_order_more_1_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for harmonious subgroups of order &gt; 1.
        /// </summary>
        internal static string str_summ_for_order_more_1_ab {
            get {
                return ResourceManager.GetString("str_summ_for_order_more_1_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for harmonious subgroups of order &gt; 1.
        /// </summary>
        internal static string str_summ_for_order_more_1_b {
            get {
                return ResourceManager.GetString("str_summ_for_order_more_1_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for harmonious subgroups of order &gt; 1.
        /// </summary>
        internal static string str_summ_for_order_more_1_bc {
            get {
                return ResourceManager.GetString("str_summ_for_order_more_1_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for harmonious subgroups of order &gt; 1.
        /// </summary>
        internal static string str_summ_for_order_more_1_c {
            get {
                return ResourceManager.GetString("str_summ_for_order_more_1_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value for harmonious subgroups of order &gt; 1.
        /// </summary>
        internal static string str_summ_for_order_more_1_ca {
            get {
                return ResourceManager.GetString("str_summ_for_order_more_1_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg φ (for 1st harmonic).
        /// </summary>
        internal static string str_tangent_p_1harm {
            get {
                return ResourceManager.GetString("str_tangent_p_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg φ (cross-conn. method).
        /// </summary>
        internal static string str_tangent_p_cross {
            get {
                return ResourceManager.GetString("str_tangent_p_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg φ (geom. method).
        /// </summary>
        internal static string str_tangent_p_geom {
            get {
                return ResourceManager.GetString("str_tangent_p_geom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg φ (ph. shift method).
        /// </summary>
        internal static string str_tangent_p_shift {
            get {
                return ResourceManager.GetString("str_tangent_p_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero sequence voltage.
        /// </summary>
        internal static string str_u_0 {
            get {
                return ResourceManager.GetString("str_u_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive sequence voltage.
        /// </summary>
        internal static string str_u_1 {
            get {
                return ResourceManager.GetString("str_u_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative sequence voltage.
        /// </summary>
        internal static string str_u_2 {
            get {
                return ResourceManager.GetString("str_u_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage, phase A.
        /// </summary>
        internal static string str_u_a {
            get {
                return ResourceManager.GetString("str_u_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 1st harmonic, phase A.
        /// </summary>
        internal static string str_u_a_1harm {
            get {
                return ResourceManager.GetString("str_u_a_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, phase A.
        /// </summary>
        internal static string str_u_a_avdirect {
            get {
                return ResourceManager.GetString("str_u_a_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage, phase A, constant component.
        /// </summary>
        internal static string str_u_a_const {
            get {
                return ResourceManager.GetString("str_u_a_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage AB.
        /// </summary>
        internal static string str_u_ab {
            get {
                return ResourceManager.GetString("str_u_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage of 1st harmonic, line AB.
        /// </summary>
        internal static string str_u_ab_1harm {
            get {
                return ResourceManager.GetString("str_u_ab_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, line AB.
        /// </summary>
        internal static string str_u_ab_avdirect {
            get {
                return ResourceManager.GetString("str_u_ab_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage, line AB, constant component.
        /// </summary>
        internal static string str_u_ab_const {
            get {
                return ResourceManager.GetString("str_u_ab_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage, phase B.
        /// </summary>
        internal static string str_u_b {
            get {
                return ResourceManager.GetString("str_u_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 1st harmonic, phase B.
        /// </summary>
        internal static string str_u_b_1harm {
            get {
                return ResourceManager.GetString("str_u_b_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, phase B.
        /// </summary>
        internal static string str_u_b_avdirect {
            get {
                return ResourceManager.GetString("str_u_b_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage, phase B, constant component.
        /// </summary>
        internal static string str_u_b_const {
            get {
                return ResourceManager.GetString("str_u_b_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage BC.
        /// </summary>
        internal static string str_u_bc {
            get {
                return ResourceManager.GetString("str_u_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage of 1st harmonic, line BC.
        /// </summary>
        internal static string str_u_bc_1harm {
            get {
                return ResourceManager.GetString("str_u_bc_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, line BC.
        /// </summary>
        internal static string str_u_bc_avdirect {
            get {
                return ResourceManager.GetString("str_u_bc_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage, line BC, constant component.
        /// </summary>
        internal static string str_u_bc_const {
            get {
                return ResourceManager.GetString("str_u_bc_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage, phase C.
        /// </summary>
        internal static string str_u_c {
            get {
                return ResourceManager.GetString("str_u_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 1st harmonic, phase C.
        /// </summary>
        internal static string str_u_c_1harm {
            get {
                return ResourceManager.GetString("str_u_c_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, phase C.
        /// </summary>
        internal static string str_u_c_avdirect {
            get {
                return ResourceManager.GetString("str_u_c_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage, phase C, constant component.
        /// </summary>
        internal static string str_u_c_const {
            get {
                return ResourceManager.GetString("str_u_c_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage CA.
        /// </summary>
        internal static string str_u_ca {
            get {
                return ResourceManager.GetString("str_u_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage of 1st harmonic, line CA.
        /// </summary>
        internal static string str_u_ca_1harm {
            get {
                return ResourceManager.GetString("str_u_ca_1harm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, line CA.
        /// </summary>
        internal static string str_u_ca_avdirect {
            get {
                return ResourceManager.GetString("str_u_ca_avdirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage, line CA, constant component.
        /// </summary>
        internal static string str_u_ca_const {
            get {
                return ResourceManager.GetString("str_u_ca_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, phase A.
        /// </summary>
        internal static string str_u_hp_a {
            get {
                return ResourceManager.GetString("str_u_hp_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, phase B.
        /// </summary>
        internal static string str_u_hp_b {
            get {
                return ResourceManager.GetString("str_u_hp_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average-rectified voltage, phase C.
        /// </summary>
        internal static string str_u_hp_c {
            get {
                return ResourceManager.GetString("str_u_hp_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 0th harmonic, phase A.
        /// </summary>
        internal static string str_u0_a {
            get {
                return ResourceManager.GetString("str_u0_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage of 0th harmonic, AB.
        /// </summary>
        internal static string str_u0_ab {
            get {
                return ResourceManager.GetString("str_u0_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 0th harmonic, phase B.
        /// </summary>
        internal static string str_u0_b {
            get {
                return ResourceManager.GetString("str_u0_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage of 0th harmonic, BC.
        /// </summary>
        internal static string str_u0_bc {
            get {
                return ResourceManager.GetString("str_u0_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 0th harmonic, phase C.
        /// </summary>
        internal static string str_u0_c {
            get {
                return ResourceManager.GetString("str_u0_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage of 0th harmonic, CA.
        /// </summary>
        internal static string str_u0_ca {
            get {
                return ResourceManager.GetString("str_u0_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 1st harmonic, phase A.
        /// </summary>
        internal static string str_u1_a {
            get {
                return ResourceManager.GetString("str_u1_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st harmonic of line voltage AB.
        /// </summary>
        internal static string str_u1_ab {
            get {
                return ResourceManager.GetString("str_u1_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 1st harmonic, phase B.
        /// </summary>
        internal static string str_u1_b {
            get {
                return ResourceManager.GetString("str_u1_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st harmonic of line voltage BC.
        /// </summary>
        internal static string str_u1_bc {
            get {
                return ResourceManager.GetString("str_u1_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage of 1st harmonic, phase C.
        /// </summary>
        internal static string str_u1_c {
            get {
                return ResourceManager.GetString("str_u1_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st harmonic of line voltage CA.
        /// </summary>
        internal static string str_u1_ca {
            get {
                return ResourceManager.GetString("str_u1_ca", resourceCulture);
            }
        }
    }
}
