//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmArchiveTree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class emstrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal emstrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmArchiveTree.emstrings", typeof(emstrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        internal static string name_avg_time_10min_full {
            get {
                return ResourceManager.GetString("name_avg_time_10min_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string name_avg_time_1min_full {
            get {
                return ResourceManager.GetString("name_avg_time_1min_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string name_avg_time_2hour_full {
            get {
                return ResourceManager.GetString("name_avg_time_2hour_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string name_avg_time_30min_full {
            get {
                return ResourceManager.GetString("name_avg_time_30min_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 seconds.
        /// </summary>
        internal static string name_avg_time_3sec_full {
            get {
                return ResourceManager.GetString("name_avg_time_3sec_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 seconds (150/180 periods).
        /// </summary>
        internal static string name_avg_time_3sec_new_full {
            get {
                return ResourceManager.GetString("name_avg_time_3sec_new_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged Network Parameters.
        /// </summary>
        internal static string name_measure_type_avg_full {
            get {
                return ResourceManager.GetString("name_measure_type_avg_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Dips and Swells .
        /// </summary>
        internal static string name_measure_type_dns_full {
            get {
                return ResourceManager.GetString("name_measure_type_dns_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Quality Parameters.
        /// </summary>
        internal static string name_measure_type_pke_full {
            get {
                return ResourceManager.GetString("name_measure_type_pke_full", resourceCulture);
            }
        }
    }
}
