//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML.Excel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pattetns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pattetns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XML.Excel.pattetns", typeof(pattetns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;DocumentProperties xmlns=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///  &lt;Title&gt;{0}&lt;/Title&gt;
        ///  &lt;Subject&gt;{1}&lt;/Subject&gt;
        ///  &lt;Author&gt;{2}&lt;/Author&gt;
        ///  &lt;LastAuthor&gt;{3}&lt;/LastAuthor&gt;
        ///  &lt;Created&gt;{4}&lt;/Created&gt;
        ///  &lt;Company&gt;{5}&lt;/Company&gt;
        ///  &lt;Version&gt;{6}&lt;/Version&gt;
        /// &lt;/DocumentProperties&gt;.
        /// </summary>
        internal static string DocumentProperties {
            get {
                return ResourceManager.GetString("DocumentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;Styles&gt;
        ///  &lt;Style ss:ID=&quot;Default&quot; ss:Name=&quot;Normal&quot;&gt;
        ///   &lt;Alignment ss:Vertical=&quot;Bottom&quot;/&gt;
        ///   &lt;Borders/&gt;
        ///   &lt;Font ss:FontName=&quot;Arial Cyr&quot; x:CharSet=&quot;204&quot;/&gt;
        ///   &lt;Interior/&gt;
        ///   &lt;NumberFormat/&gt;
        ///   &lt;Protection/&gt;
        ///  &lt;/Style&gt;
        ///  &lt;Style ss:ID=&quot;EmHeader&quot;&gt;   
        ///   &lt;Alignment ss:Horizontal=&quot;Center&quot; ss:Vertical=&quot;Bottom&quot;/&gt;
        ///   &lt;Borders&gt;
        ///    &lt;Border ss:Position=&quot;Bottom&quot; ss:LineStyle=&quot;Continuous&quot; ss:Weight=&quot;1&quot;/&gt;
        ///    &lt;Border ss:Position=&quot;Left&quot; ss:LineStyle=&quot;Continuous&quot; ss:Weight=&quot;1&quot;/&gt;
        ///    &lt;Border ss:Position=&quot;Right [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/Workbook&gt;
        ///.
        /// </summary>
        internal static string WorkbookFooter {
            get {
                return ResourceManager.GetString("WorkbookFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;?mso-application progid=&quot;Excel.Sheet&quot;?&gt;
        ///&lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        /// xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        /// xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        /// xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        /// xmlns:html=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;.
        /// </summary>
        internal static string WorkbookHeader {
            get {
                return ResourceManager.GetString("WorkbookHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WorksheetOptions xmlns=&quot;urn:schemas-microsoft-com:office:excel&quot;&gt;
        ///   &lt;PageSetup&gt;
        ///    &lt;PageMargins/&gt;
        ///   &lt;/PageSetup&gt;
        ///   &lt;Selected/&gt;
        ///   &lt;ProtectObjects&gt;False&lt;/ProtectObjects&gt;
        ///   &lt;ProtectScenarios&gt;False&lt;/ProtectScenarios&gt;
        ///  &lt;/WorksheetOptions&gt;.
        /// </summary>
        internal static string WorksheetOptions {
            get {
                return ResourceManager.GetString("WorksheetOptions", resourceCulture);
            }
        }
    }
}
